### ISSUE TITLE
It this completed

### ISSUE THREAD

**Issue by BastinRobin** [thavelick/summarize#3]
Hi is this module is production ready?

**Comment by thavelick** [comment]
Hi Bastin,

The module does work, and is not currently under active development (simply because it does what I needed it to do).  The question of whether is "production ready" is entirely your call.  If it does what you need, then yes; I'd say it is production ready.  If you're worried, I'd suggest reading through the code.  It is actually quite simple.

If you do find any bugs, or have suggestions on how it can be improved, I'd be happy to hear about them.

Thanks,

Tristan
